; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = no_ota.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921000
board_build.arduino.memory_type = dio_opi
board_build.flash_mode = dio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.extra_flags = -DBOARD_HAS_PSRAM
lib_deps = 
	lvgl/lvgl@9.4.0
	lovyan03/LovyanGFX@^1.2.19
build_flags = 
	-DCORE_DEBUG_LEVEL=3
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DLV_CONF_INCLUDE_SIMPLE
	;-DWIFI_LOGGING_ENABLE=1
	;-DWIFI_LOGGING_UDP_IP=\"192.168.0.249\"
	;-DWIFI_LOGGING_UDP_PORT=10514
	;-DCSV_OUT=1

[env:esp32_s3]
build_flags = 
	${env.build_flags}
	-I include
	-DINFO
	-DWARN
	-DERR
