#include "ui/UiDemo.hpp"

#include "display/BoardDisplay.hpp"
#include "log_core.h"

namespace ui {

/**
 * @brief Convert a touch event state into a short diagnostic label.
 *
 * @param state Touch event state that should be translated.
 *
 * @return Static text representation of the given event state.
 */
const char* UiDemo::touchEventLabel(TouchEventState state) const {
    switch (state) {
        case TouchEventState::Idle:
            return "IDLE";
        case TouchEventState::Press:
            return "PRESS";
        case TouchEventState::Move:
            return "MOVE";
        case TouchEventState::Hold:
            return "HOLD";
        case TouchEventState::Release:
            return "RELEASE";
        default:
            return "UNKNOWN";
    }
}

/**
 * @brief Emit a log line that reflects the current touch diagnostics state.
 */
void UiDemo::logTouchState() const {
    INFO_TAG(
        "TOUCH",
        "event=%s x=%u y=%u active=%s\n",
        touchEventLabel(touch_event_state_),
        last_touch_x_,
        last_touch_y_,
        is_touch_active_ ? "yes" : "no");
}

/**
 * @brief Copy one invalidated LVGL area to the physical LovyanGFX display.
 *
 * @param display_handle LVGL display that requests the flush.
 * @param area Dirty area in LVGL logical coordinates.
 * @param pixel_map Pointer to RGB565 pixel data generated by LVGL.
 */
void UiDemo::displayFlushCallback(lv_display_t* display_handle, const lv_area_t* area, uint8_t* pixel_map) {
    UiDemo* instance = static_cast<UiDemo*>(lv_display_get_user_data(display_handle));
    const int32_t width = area->x2 - area->x1 + 1;
    const int32_t height = area->y2 - area->y1 + 1;

    instance->display_.pushImage(
        area->x1,
        area->y1,
        width,
        height,
        reinterpret_cast<const uint16_t*>(pixel_map));

    lv_display_flush_ready(display_handle);
}

/**
 * @brief Read one touch sample from the board touch controller and forward it into LVGL.
 *
 * @param input_handle LVGL input device requesting the current touch state.
 * @param data Output structure that receives the pointer state and coordinates.
 */
void UiDemo::touchReadCallback(lv_indev_t* input_handle, lv_indev_data_t* data) {
    UiDemo* instance = static_cast<UiDemo*>(lv_indev_get_user_data(input_handle));

    uint16_t x = instance->last_touch_x_;
    uint16_t y = instance->last_touch_y_;
    const bool touched = instance->display_.getTouch(&x, &y) > 0;
    const TouchEventState previous_state = instance->touch_event_state_;

    if (touched) {
        if (!instance->is_touch_active_) {
            instance->touch_event_state_ = TouchEventState::Press;
        } else if (x != instance->previous_touch_x_ || y != instance->previous_touch_y_) {
            instance->touch_event_state_ = TouchEventState::Move;
        } else {
            instance->touch_event_state_ = TouchEventState::Hold;
        }

        instance->last_touch_x_ = x;
        instance->last_touch_y_ = y;
        instance->previous_touch_x_ = x;
        instance->previous_touch_y_ = y;
        instance->is_touch_active_ = true;
        data->state = LV_INDEV_STATE_PRESSED;
        data->point.x = x;
        data->point.y = y;
    } else {
        if (instance->is_touch_active_) {
            instance->touch_event_state_ = TouchEventState::Release;
        } else {
            instance->touch_event_state_ = TouchEventState::Idle;
        }

        instance->is_touch_active_ = false;
        data->state = LV_INDEV_STATE_RELEASED;
        data->point.x = instance->last_touch_x_;
        data->point.y = instance->last_touch_y_;
    }

    if (instance->touch_event_state_ != previous_state) {
        instance->logTouchState();
    }
}

/**
 * @brief React to LVGL button clicks by loading the screen encoded in the button user data.
 *
 * @param event LVGL event object generated by a screen navigation button.
 */
void UiDemo::navigationEventCallback(lv_event_t* event) {
    const lv_event_code_t code = lv_event_get_code(event);
    if (code != LV_EVENT_CLICKED && code != LV_EVENT_SHORT_CLICKED && code != LV_EVENT_RELEASED) {
        return;
    }

    UiDemo* instance = static_cast<UiDemo*>(lv_event_get_user_data(event));
    lv_obj_t* button = static_cast<lv_obj_t*>(lv_event_get_target(event));
    const ScreenId target = static_cast<ScreenId>(reinterpret_cast<uintptr_t>(lv_obj_get_user_data(button)));
    instance->activateScreen(target);
}

} // namespace ui
